apiVersion: v1
kind: Service
metadata:
  name: wizard-ip
spec:
  ports:
    - name: wizard
      port: 80
      protocol: TCP
      targetPort: 30080
  clusterIP: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizard-service
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wizard-ip
                port:
                  name: wizard
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wizard-ip
subsets:
  - addresses:
      # This ip is a placeholder and will be replaced by a patch during launch
      # k3s kubectl patch endpoints wizard-ip --type merge --patch '{"subsets": [{"addresses": [{"ip": "'$(hostname -i)'"}],"ports": [{"name": "wizard","port": 30080,"protocol": "TCP"}]}]}'
      - ip: 10.10.0.0
    ports:
      - name: wizard
        port: 30080
        protocol: TCP
