apiVersion: v1
kind: Service
metadata:
  name: wizard-ip
spec:
  ports:
    - name: wizard
      port: 80
      protocol: TCP
      targetPort: 30080
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wizard-ip
subsets:
  - addresses:
      - ip: 10.10.0.0
    ports:
      - name: wizard
        port: 30080
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wizard-service
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wizard-ip
                port:
                  name: wizard
